version: '3.8'

services:
  app:
    image: "chany91/nbbang:latest"
    container_name: nbbang-be
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${db_url}
      - SPRING_DATASOURCE_USERNAME=${db_user}
      - SPRING_DATASOURCE_PASSWORD=${db_password}
      - SPRING_REDIS_HOST=${redis_host}
      - SPRING_REDIS_PORT=${redis_port}
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server-new
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
