name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER }}
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          ssh -i $PRIVATE_KEY $USERNAME@$HOST << 'EOF'
          cd /var/www/nbbang-be
          git pull origin main
          ./gradlew build --exclude-task test
          java -jar build/libs/nbbang-0.0.1-SNAPSHOT.jar &
          EOF
