name: Docker-based Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nbbang:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to Server via SSH and Run Container
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem -tt $USERNAME@$HOST <<EOF
            echo "$SSH_PASSWORD" | sudo -S docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nbbang:latest
          
            # Redis 컨테이너가 실행 중인지 확인
            if [ "$(sudo docker ps -q -f name=redis-server-new)" ]; then
              echo "Redis 컨테이너가 이미 실행 중입니다. 재사용합니다."
            else
              echo "Redis 컨테이너가 실행 중이 아닙니다. 새로 실행합니다."
              echo "$SSH_PASSWORD" | sudo -S docker-compose up -d redis-server-new
            fi

            # 기존 nbbang 컨테이너 중지 및 제거
            if [ "$(sudo docker ps -q -f name=nbbang)" ]; then
              echo "$SSH_PASSWORD" | sudo -S docker stop nbbang
              echo "$SSH_PASSWORD" | sudo -S docker rm nbbang
            fi

            # 새로운 컨테이너 실행
            cd /var/www
            echo "$SSH_PASSWORD" | sudo -S docker-compose up -d www-app-1

            # nbbang 컨테이너에 자동 재시작 설정
            echo "$SSH_PASSWORD" | sudo -S docker update --restart always www-app-1
          EOF
          rm private_key.pem
